### ISSUE TITLE
This lib has no logic structure

### ISSUE THREAD

**Issue by alan-andrade** [wellnessfx/white_rabbit#1]
this is a mess, not easy to extend, but looking forward to make it better. Its a super handy tool.

**Comment by alan-andrade** [comment]
Read those words. What a shame @mogox :'(

**Comment by mogox** [comment]
Haha! I feel the same way by reading the code we wrote.  It's just part of learning and dealing with priorities versus feature and product ideas, always hoping for the best with the resources we have.

You are an awesome developer, you just want to be better :sparkling_heart: :
